# .github/workflows/deploy.yml
name: Build & Deploy (SFTP)

on:
  push:
    branches: [master, main]
  workflow_dispatch:

# Prevent overlapping deploys on the same branch
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build (Vite)
        run: npm run build
        # Vite outputs to dist/ by default

      - name: Add host to known_hosts
        env:
          HOST: ${{ secrets.SFTP_HOST }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.SFTP_HOST }} # e.g. yourdomain.com or server name
          port: 22
          username: ${{ secrets.SFTP_USER }} # your webspace user
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "dist/*"
          remote_path: "public_html/"
          delete_remote_files: false # set to true to prune removed files

      - name: Smoke test (list remote dir)
        env:
          HOST: ${{ secrets.SFTP_HOST }}
          USER: ${{ secrets.SFTP_USER }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$KEY" > key && chmod 600 key
          ssh -o PreferredAuthentications=publickey,password -i key "$USER@$HOST" "ls -la public_html | tail -n +1"
