name: Build & Deploy (SFTP)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (Vite)
        run: npm run build
        # dist/ is the Vite output; if you changed it, update below too.

      - name: Prepare SSH known_hosts
        env:
          HOST: ${{ secrets.SFTP_HOST }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

      - name: Deploy via SFTP
        # Simple, reliable SFTP sync action
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: 22
          username: ${{ secrets.SFTP_USER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "dist/*"
          remote_path: "public_html/"
          delete_remote_files: false
          # If your host prompts for password after key, enable the next two lines:
          # args: "-o PreferredAuthentications=publickey,password"
          # password: ${{ secrets.SFTP_PASSWORD }}

      - name: Smoke test: list remote dir
        env:
          HOST: ${{ secrets.SFTP_HOST }}
          USER: ${{ secrets.SFTP_USER }}
          KEY:  ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$KEY" > key && chmod 600 key
          ssh -o PreferredAuthentications=publickey,password -i key "$USER@$HOST" "ls -la public_html | tail -n +1"
